version: "3.8"
services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    volumes:
      - mysql-data:/var/lib/mysql # 修正されたボリューム名
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword
      MYSQL_DATABASE: myapp
      # MYSQL_USER: root
      MYSQL_PASSWORD: mysecurepassword

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo" # 日本時間に設定
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp # 修正されたパス
    environment:
      TZ: "Asia/Tokyo" # 日本時間に設定
    depends_on:
      - db
      - redis
  redis:
    image: redis
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  mysql-data: # 修正されたボリューム名
    driver: local
